name: Flutter Trigger Test

on:
  push:
    branches:
      - main

jobs:
  run-on-main-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checked
        run: echo "A new commit was pushed to main"

      - name: Show Commit Triggered
        run: echo "Workflow triggered successfully"
