name: Flutter Dev APK Build

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'

      - name: Install Packages
        run: flutter pub get

      - name: Build Dev Debug APK
        run: flutter build apk --debug --flavor dev

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: junto-dev-debug-apk
          path: build/app/outputs/flutter-apk/*.apk
